# Generated by Django 5.1.2 on 2025-04-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_convert_durations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedata',
            name='rating',
        ),
        migrations.AddField(
            model_name='moviedata',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
