# Generated by Django 5.1.2 on 2025-05-03 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_discussiontopic_discussionpost_userfollowing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussiontopic',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='discussiontopic',
            name='related_movie',
        ),
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='following_user',
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='user',
        ),
        migrations.DeleteModel(
            name='DiscussionPost',
        ),
        migrations.DeleteModel(
            name='DiscussionTopic',
        ),
        migrations.DeleteModel(
            name='UserFollowing',
        ),
    ]
